define SRC_SCHEMA=&1
define DST_SCHEMA=&2

SELECT * FROM (SELECT owner, object_type, 1 CNT FROM all_objects WHERE owner IN ('&SRC_SCHEMA','&DST_SCHEMA')) e PIVOT( sum(CNT) FOR object_type IN ('TRIGGER','SYNONYM','PACKAGE','PACKAGE BODY','VIEW','MATERIALIZED VIEW','TABLE','INDEX','FUNCTION','PROCEDURE')) ORDER BY owner;
